[tool.poetry]
name = "python-template-repo"
version = "0.1.0"
description = ""
authors = ["Maximilian Jugl <Maximilian.Jugl@medizin.uni-leipzig.de>"]
readme = "README.md"
packages = [{ include = "project" }]

[tool.poetry.scripts]
flame-result = "project.main:cli"

[tool.poetry.dependencies]
python = "^3.11"
minio = "^7.2.3"
fastapi = "^0.109.1"
uvicorn = { extras = ["standard"], version = "^0.27.0" }
pydantic-settings = "^2.1.0"
python-multipart = "^0.0.6"
click = "^8.1.7"
jwcrypto = "^1.5.1"
httpx = "^0.26.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.3"
ruff = "^0.1.8"
pre-commit = "^3.6.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
