services:

  minio:
    image: quay.io/minio/minio:RELEASE.2024-01-16T16-07-38Z
    volumes:
      - minio-data:/mnt/data
      - minio-config:/etc/config
    environment:
      - MINIO_VOLUMES=/mnt/data
      - MINIO_CONFIG_ENV_FILE=/etc/config/.env
    env_file:
      - .env
    ports:
      - "9000:9000"  # s3 api
      - "9001:9001"  # web console
    command: [ "server", "--console-address", ":9001" ]

volumes:
  minio-data:
  minio-config:
