services:

  minio:
    image: bitnami/minio:2024.12.13
    environment:
      - MINIO_DEFAULT_BUCKETS=flame
    env_file:
      - .env
    ports:
      - "9000:9000"  # s3 api
      - "9001:9001"  # web console

  postgres:
    image: postgres:17.2
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
